### ISSUE TITLE
ASCII equivalents for special characters

### ISSUE THREAD

**Issue by gianpietro1** [dhruvasagar/soulmate_rails#5]
Hi, I've found out that when searching for a non-ASCII character everything works fine, but it would be ideal to search for the ASCII "equivalent" as well.
For example, when searching for "félix", it would be ideal that "felix" worked as well.  
A more critical case happens when there is a capital letter like in "Índigo", because "índigo" (downcase í) does not work, it requires the capital letter to be searched.  In this case t would be ideal that searching for "indigo" or "índigo" worked as well.

**Comment by gianpietro1** [comment]
I realized I need to solve this with accent folding in jquery, thanks anyway!

**Comment by dhruvasagar** [comment]
Nice to know, thanks
